---
:concurrency: 10
:queues:
  - [low_priority, 1]
  - [starting_bots, 1]
  - [api_keys_validation, 1]
  - [mailers, 1]
  - [binance, 2]
  - [binance_us, 2]
  - [coinbase, 2]
  - [kraken, 2]
  - [default, 1]
:limits:
  low_priority: 1
  binance: 1
  binance_us: 1
  coinbase: 1
  kraken: 1